// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: schemas/protos/v1/user.proto

package protosv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	v1 "nnyd-back/pb/schemas/protos/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "schemas.protos.v1.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceCreateUserProcedure is the fully-qualified name of the UserService's CreateUser RPC.
	UserServiceCreateUserProcedure = "/schemas.protos.v1.UserService/CreateUser"
	// UserServiceUpdateUserProcedure is the fully-qualified name of the UserService's UpdateUser RPC.
	UserServiceUpdateUserProcedure = "/schemas.protos.v1.UserService/UpdateUser"
	// UserServiceDeleteUserProcedure is the fully-qualified name of the UserService's DeleteUser RPC.
	UserServiceDeleteUserProcedure = "/schemas.protos.v1.UserService/DeleteUser"
	// UserServiceGetMeProcedure is the fully-qualified name of the UserService's GetMe RPC.
	UserServiceGetMeProcedure = "/schemas.protos.v1.UserService/GetMe"
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/schemas.protos.v1.UserService/GetUser"
	// UserServiceGetUsersProcedure is the fully-qualified name of the UserService's GetUsers RPC.
	UserServiceGetUsersProcedure = "/schemas.protos.v1.UserService/GetUsers"
	// UserServiceCheckDisplayNameProcedure is the fully-qualified name of the UserService's
	// CheckDisplayName RPC.
	UserServiceCheckDisplayNameProcedure = "/schemas.protos.v1.UserService/CheckDisplayName"
	// UserServiceFollowUserProcedure is the fully-qualified name of the UserService's FollowUser RPC.
	UserServiceFollowUserProcedure = "/schemas.protos.v1.UserService/FollowUser"
	// UserServiceUnfollowUserProcedure is the fully-qualified name of the UserService's UnfollowUser
	// RPC.
	UserServiceUnfollowUserProcedure = "/schemas.protos.v1.UserService/UnfollowUser"
)

// UserServiceClient is a client for the schemas.protos.v1.UserService service.
type UserServiceClient interface {
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.DeleteUserResponse], error)
	GetMe(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.GetUserResponse], error)
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	GetUsers(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.GetUsersResponse], error)
	CheckDisplayName(context.Context, *connect.Request[v1.CheckDisplayNameRequest]) (*connect.Response[v1.CheckDisplayNameResponse], error)
	FollowUser(context.Context, *connect.Request[v1.FollowUserRequest]) (*connect.Response[v1.FollowUserResponse], error)
	UnfollowUser(context.Context, *connect.Request[v1.UnfollowUserRequest]) (*connect.Response[v1.UnfollowUserResponse], error)
}

// NewUserServiceClient constructs a client for the schemas.protos.v1.UserService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &userServiceClient{
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+UserServiceCreateUserProcedure,
			opts...,
		),
		updateUser: connect.NewClient[v1.UpdateUserRequest, v1.UpdateUserResponse](
			httpClient,
			baseURL+UserServiceUpdateUserProcedure,
			opts...,
		),
		deleteUser: connect.NewClient[emptypb.Empty, v1.DeleteUserResponse](
			httpClient,
			baseURL+UserServiceDeleteUserProcedure,
			opts...,
		),
		getMe: connect.NewClient[emptypb.Empty, v1.GetUserResponse](
			httpClient,
			baseURL+UserServiceGetMeProcedure,
			opts...,
		),
		getUser: connect.NewClient[v1.GetUserRequest, v1.GetUserResponse](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			opts...,
		),
		getUsers: connect.NewClient[emptypb.Empty, v1.GetUsersResponse](
			httpClient,
			baseURL+UserServiceGetUsersProcedure,
			opts...,
		),
		checkDisplayName: connect.NewClient[v1.CheckDisplayNameRequest, v1.CheckDisplayNameResponse](
			httpClient,
			baseURL+UserServiceCheckDisplayNameProcedure,
			opts...,
		),
		followUser: connect.NewClient[v1.FollowUserRequest, v1.FollowUserResponse](
			httpClient,
			baseURL+UserServiceFollowUserProcedure,
			opts...,
		),
		unfollowUser: connect.NewClient[v1.UnfollowUserRequest, v1.UnfollowUserResponse](
			httpClient,
			baseURL+UserServiceUnfollowUserProcedure,
			opts...,
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	createUser       *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	updateUser       *connect.Client[v1.UpdateUserRequest, v1.UpdateUserResponse]
	deleteUser       *connect.Client[emptypb.Empty, v1.DeleteUserResponse]
	getMe            *connect.Client[emptypb.Empty, v1.GetUserResponse]
	getUser          *connect.Client[v1.GetUserRequest, v1.GetUserResponse]
	getUsers         *connect.Client[emptypb.Empty, v1.GetUsersResponse]
	checkDisplayName *connect.Client[v1.CheckDisplayNameRequest, v1.CheckDisplayNameResponse]
	followUser       *connect.Client[v1.FollowUserRequest, v1.FollowUserResponse]
	unfollowUser     *connect.Client[v1.UnfollowUserRequest, v1.UnfollowUserResponse]
}

// CreateUser calls schemas.protos.v1.UserService.CreateUser.
func (c *userServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// UpdateUser calls schemas.protos.v1.UserService.UpdateUser.
func (c *userServiceClient) UpdateUser(ctx context.Context, req *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DeleteUser calls schemas.protos.v1.UserService.DeleteUser.
func (c *userServiceClient) DeleteUser(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// GetMe calls schemas.protos.v1.UserService.GetMe.
func (c *userServiceClient) GetMe(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.GetUserResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// GetUser calls schemas.protos.v1.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// GetUsers calls schemas.protos.v1.UserService.GetUsers.
func (c *userServiceClient) GetUsers(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.GetUsersResponse], error) {
	return c.getUsers.CallUnary(ctx, req)
}

// CheckDisplayName calls schemas.protos.v1.UserService.CheckDisplayName.
func (c *userServiceClient) CheckDisplayName(ctx context.Context, req *connect.Request[v1.CheckDisplayNameRequest]) (*connect.Response[v1.CheckDisplayNameResponse], error) {
	return c.checkDisplayName.CallUnary(ctx, req)
}

// FollowUser calls schemas.protos.v1.UserService.FollowUser.
func (c *userServiceClient) FollowUser(ctx context.Context, req *connect.Request[v1.FollowUserRequest]) (*connect.Response[v1.FollowUserResponse], error) {
	return c.followUser.CallUnary(ctx, req)
}

// UnfollowUser calls schemas.protos.v1.UserService.UnfollowUser.
func (c *userServiceClient) UnfollowUser(ctx context.Context, req *connect.Request[v1.UnfollowUserRequest]) (*connect.Response[v1.UnfollowUserResponse], error) {
	return c.unfollowUser.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the schemas.protos.v1.UserService service.
type UserServiceHandler interface {
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.DeleteUserResponse], error)
	GetMe(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.GetUserResponse], error)
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	GetUsers(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.GetUsersResponse], error)
	CheckDisplayName(context.Context, *connect.Request[v1.CheckDisplayNameRequest]) (*connect.Response[v1.CheckDisplayNameResponse], error)
	FollowUser(context.Context, *connect.Request[v1.FollowUserRequest]) (*connect.Response[v1.FollowUserResponse], error)
	UnfollowUser(context.Context, *connect.Request[v1.UnfollowUserRequest]) (*connect.Response[v1.UnfollowUserResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceCreateUserHandler := connect.NewUnaryHandler(
		UserServiceCreateUserProcedure,
		svc.CreateUser,
		opts...,
	)
	userServiceUpdateUserHandler := connect.NewUnaryHandler(
		UserServiceUpdateUserProcedure,
		svc.UpdateUser,
		opts...,
	)
	userServiceDeleteUserHandler := connect.NewUnaryHandler(
		UserServiceDeleteUserProcedure,
		svc.DeleteUser,
		opts...,
	)
	userServiceGetMeHandler := connect.NewUnaryHandler(
		UserServiceGetMeProcedure,
		svc.GetMe,
		opts...,
	)
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		opts...,
	)
	userServiceGetUsersHandler := connect.NewUnaryHandler(
		UserServiceGetUsersProcedure,
		svc.GetUsers,
		opts...,
	)
	userServiceCheckDisplayNameHandler := connect.NewUnaryHandler(
		UserServiceCheckDisplayNameProcedure,
		svc.CheckDisplayName,
		opts...,
	)
	userServiceFollowUserHandler := connect.NewUnaryHandler(
		UserServiceFollowUserProcedure,
		svc.FollowUser,
		opts...,
	)
	userServiceUnfollowUserHandler := connect.NewUnaryHandler(
		UserServiceUnfollowUserProcedure,
		svc.UnfollowUser,
		opts...,
	)
	return "/schemas.protos.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceCreateUserProcedure:
			userServiceCreateUserHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserProcedure:
			userServiceUpdateUserHandler.ServeHTTP(w, r)
		case UserServiceDeleteUserProcedure:
			userServiceDeleteUserHandler.ServeHTTP(w, r)
		case UserServiceGetMeProcedure:
			userServiceGetMeHandler.ServeHTTP(w, r)
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceGetUsersProcedure:
			userServiceGetUsersHandler.ServeHTTP(w, r)
		case UserServiceCheckDisplayNameProcedure:
			userServiceCheckDisplayNameHandler.ServeHTTP(w, r)
		case UserServiceFollowUserProcedure:
			userServiceFollowUserHandler.ServeHTTP(w, r)
		case UserServiceUnfollowUserProcedure:
			userServiceUnfollowUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.CreateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.UpdateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) DeleteUser(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.DeleteUser is not implemented"))
}

func (UnimplementedUserServiceHandler) GetMe(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.GetMe is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUsers(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.GetUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.GetUsers is not implemented"))
}

func (UnimplementedUserServiceHandler) CheckDisplayName(context.Context, *connect.Request[v1.CheckDisplayNameRequest]) (*connect.Response[v1.CheckDisplayNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.CheckDisplayName is not implemented"))
}

func (UnimplementedUserServiceHandler) FollowUser(context.Context, *connect.Request[v1.FollowUserRequest]) (*connect.Response[v1.FollowUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.FollowUser is not implemented"))
}

func (UnimplementedUserServiceHandler) UnfollowUser(context.Context, *connect.Request[v1.UnfollowUserRequest]) (*connect.Response[v1.UnfollowUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.protos.v1.UserService.UnfollowUser is not implemented"))
}
