services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/db/conf/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

  api:
    image: golang:1.21.1
    volumes:
      - .:/opt/nnyd
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: null
